### ISSUE TITLE
文章收录标准

### ISSUE THREAD

**Issue by Guanchishan** [Guanchishan/Storia-di-Hokchew#4]
暂时没有想好，但是想把这样东拼西凑的小编文删了：
https://github.com/Guanchishan/Storia-di-Hokchew/blob/master/%E4%BB%8A%E5%A4%A9%E7%99%BD%E9%9C%B2%EF%BC%81%E7%A6%8F%E5%B7%9E%E4%BA%BA%E4%B8%80%E5%AE%9A%E8%A6%81%E5%90%83%E8%BF%99%E4%B8%AA%EF%BC%8C%E4%B8%80%E9%A2%97%E9%A1%B6%E4%B8%80%E5%8F%AA%E8%80%81%E6%AF%8D%E9%B8%A1%EF%BC%81.md

**Comment by ztl8702** [comment]
我觉得不妨留着。我们未来（如果有足够用户），可用用户交互（点赞数、访问时长）等方式来间接衡量文章质量。类似[Hacker News](https://zh.wikipedia.org/wiki/Hacker_News) 的机制：什么都能提交，靠用户筛选。


我们“死的原则”越简单越好：比如只要求确实是和福州话/闽东语相关。（人工审核的成本最低）

**Comment by Guanchishan** [comment]
倒也可以。

而且摘录文章以后最好是能机器摘。


Radium <notifications@github.com> 于 2020年9月2日周三 上午1:53写道：
